# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'sinatra', '~> 3.0', '>= 3.0.5'
gem 'activerecord', '~> 7.0', '>= 7.0.4.2'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.26'
gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'sqlite3', '~> 1.6', '>= 1.6.1'

gem 'require_all', '~> 3.0'

gem 'puma', '~> 6.1'
gem 'thin', '~> 1.8', '>= 1.8.1'

group :development do
    gem "pry"
    gem "rerun"
end

group :production do
    gem "pg"
end
  

